### ISSUE TITLE
ミラーリポジトリでのPublish

### ISSUE THREAD

**Issue by TaikiHoshika** [TaikiHoshika/example-package#1]
# 前提
## デモリポジトリ
元リポジトリ: https://github.com/TaikiHoshika/example-package
ミラーリポジトリ: https://github.com/TaikiHoshika/example-package-mirror

## 用語
元となるリポジトリを`リポジトリA`、ミラーリポジトリを`リポジトリB`と呼称する

# 問題
リポジトリAと、リポジトリBで同一のパッケージ名を使用しPushlishを試みた場合、名前空間が衝突しリポジトリB側ではPublishに失敗する。
そのためパッケージ名をそれぞれで変更し解決を試みる。

# 手順
## ミラー設定
1. GitHubからミラーリポジトリであるリポジトリBを作成する
2. リポジトリAにリポジトリBの参照を追加
```
cd repository-a
git remote add origin-b https://@github.com/user/repository-b.git
```
3. リポジトリBへミラープッシュを行う
```
git push origin-b --mirror
```

## Publish準備
今回はGithub Actionsを使用しPublishを行う。
前述した問題のため、環境変数とGitHub Actionsを使用してパッケージ名を変更する
- パッケージ名
- リポジトリURL

使用するActionsのファイルは以下2種類である
```yml
# .github/workflows/publish.yml
name: publish package

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Package Infomation
        run: |
          node .github/workflows/setPackageInfomation.ts package.json ${{ github.repository_owner }} ${{ vars.PACKAGE_NAME }} ${{ vars.REPOSITORY_URL }}

      - name: Publish Package
        run: npm publish
        env:
          GITHUB_PACKAGES_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
```ts
// .github/workflows/setPackageInfomation.ts
const fs = require("fs");
const path = require("path");

const data = JSON.parse(fs.readFileSync(process.argv[2], "utf8"));
data["name"] = `@${process.argv[3]}/${process.argv[4]}`;
data["repository"]["url"] = process.argv[5];

fs.writeFileSync(process.argv[2], JSON.stringify(data), "utf8");
```

1. リポジトリのActions Environment Variablesに以下2つの値を追加する

| Name | Value |
| - | - |
| PACKAGE_NAME | リポジトリ名 |
| REPOSITORY_URL | リポジトリURL.git |

以下設定例
リポジトリA (https://github.com/TaikiHoshika/example-package/settings/variables/actions)
![image](https://github.com/user-attachments/assets/0bbfe5e7-d285-4ce1-b065-924f571f81b9)

リポジトリB (https://github.com/TaikiHoshika/example-package-mirror)
![image](https://github.com/user-attachments/assets/d0461770-08ee-48ae-a537-e12b641c0a9f)

2. リリースを作成する
3. パッケージが作成されたかを確認する

# 懸念点
今回はGitHub Actionsを使用し、パッケージ名を変更するようにしているが、リポジトリBのパッケージを使用したい場合は依存関係を変更する必要が出てくる。

![image](https://github.com/user-attachments/assets/6a1e2b15-57a5-4243-b57b-bc69fa46f986)

また、タグやリリースが同期されたとしても、パッケージのPublishは同期されないため解決法を探る必要がある。
